# Generated by Django 5.1.4 on 2024-12-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfRooms', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('story', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDeposit', models.BooleanField()),
                ('isPetFriendly', models.BooleanField()),
                ('isForSmokers', models.BooleanField()),
                ('isForStudents', models.BooleanField()),
                ('isForWorkers', models.BooleanField()),
                ('isMoveImmediate', models.BooleanField()),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasElevator', models.BooleanField()),
                ('hasBalcony', models.BooleanField()),
                ('hasAC', models.BooleanField()),
                ('hasPhone', models.BooleanField()),
                ('hasTV', models.BooleanField()),
                ('hasInternet', models.BooleanField()),
                ('hasIntercom', models.BooleanField()),
                ('hasSurveillance', models.BooleanField()),
                ('hasParking', models.BooleanField()),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
        ),
    ]
