# Generated by Django 5.1.4 on 2024-12-19 19:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(default=datetime.datetime(2024, 12, 19, 19, 29, 31, 183142, tzinfo=datetime.timezone.utc))),
                ('date_updated', models.DateField(null=True)),
                ('has_images', models.BooleanField()),
                ('move_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=32)),
                ('street_num', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_rooms', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('story', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('OG', 'ORIGINAL'), ('NE', 'NEW'), ('RE', 'RENOVATED'), ('LU', 'LUX')], default='OG', max_length=2)),
                ('furnishing', models.CharField(choices=[('FU', 'FURNISHED'), ('SF', 'SEMI_FURNISHED'), ('EM', 'EMPTY')], default='FU', max_length=2)),
                ('heating', models.CharField(choices=[('DH', 'DISTRICT'), ('FH', 'FLOOR'), ('SH', 'STORAGE_HEATER'), ('GA', 'GAS'), ('TS', 'TILED_STOVE'), ('HP', 'HEAT_PUMP')], default='DH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('website', models.CharField(max_length=48)),
                ('email', models.EmailField(max_length=64)),
                ('registration_date', models.DateField(default=datetime.datetime(2024, 12, 19, 19, 29, 31, 184269, tzinfo=datetime.timezone.utc))),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.address')),
                ('posted_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.ad')),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='conditions',
            field=models.ManyToManyField(to='apartments.condition'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='contents',
            field=models.ManyToManyField(to='apartments.content'),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('posted_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.ad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
