# Generated by Django 5.1.4 on 2024-12-19 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 19, 29, 56, 327477, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agency',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 19, 29, 56, 328653, tzinfo=datetime.timezone.utc)),
        ),
    ]
