# Generated by Django 5.1.4 on 2024-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='furnishing',
            field=models.CharField(choices=[('FU', 'FURNISHED'), ('SF', 'SEMI_FURNISHED'), ('EM', 'EMPTY')], default='FU', max_length=2),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('DH', 'DISTRICT'), ('FH', 'FLOOR'), ('SH', 'STORAGE_HEATER'), ('GA', 'GAS'), ('TS', 'TILED_STOVE'), ('HP', 'HEAT_PUMP')], default='DH', max_length=2),
        ),
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('OG', 'ORIGINAL'), ('NE', 'NEW'), ('RE', 'RENOVATED'), ('LU', 'LUX')], default='OG', max_length=2),
        ),
    ]
