# Generated by Django 5.1.4 on 2024-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='liked_ads',
            field=models.ManyToManyField(related_name='liked_ads', to='apartments.ad'),
        ),
        migrations.AddField(
            model_name='account',
            name='posted_ads',
            field=models.ManyToManyField(related_name='posted_ads', to='apartments.ad'),
        ),
    ]
