# Generated by Django 5.1.4 on 2024-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_furnishing_apartment_heating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='apartment',
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('apartment', models.ManyToManyField(to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('apartment', models.ManyToManyField(to='apartments.apartment')),
            ],
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
