# Generated by Django 5.1.4 on 2024-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_profile_rename_numofrooms_apartment_num_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
