# Generated by Django 5.1.4 on 2024-12-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_landlord_email_alter_agency_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='name',
        ),
    ]
