# Generated by Django 5.1.4 on 2024-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_remove_agency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
