# Generated by Django 5.1.4 on 2024-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='furnishing',
            field=models.CharField(choices=[('EM', 'Prazno'), ('FU', 'Namešteno'), ('SF', 'Polunamešteno')], default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('DI', 'Gradsko'), ('FL', 'Etažno'), ('GA', 'Gas'), ('HP', 'Toplotna pumpa'), ('SH', 'TA'), ('TS', 'Kaljeva peć')], default='DI', max_length=2),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('OG', 'Izvorno'), ('NE', 'Novo'), ('LU', 'Lux'), ('RE', 'Renovirano')], default='OG', max_length=2),
        ),
    ]
