# Generated by Django 5.1.4 on 2024-12-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartment_furnishing_alter_apartment_heating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='apartments',
            field=models.ManyToManyField(to='apartments.ad'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='apartments',
            field=models.ManyToManyField(to='apartments.ad'),
        ),
    ]
