# Generated by Django 5.1.4 on 2024-12-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_agency_apartments_landlord_apartments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='apartments',
            new_name='ads',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='apartments',
            new_name='ads',
        ),
    ]
