# Generated by Django 5.1.4 on 2024-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_rename_apartments_agency_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='liked_ads',
            field=models.ManyToManyField(related_name='liked_ads', to='apartments.ad'),
        ),
    ]
